### ISSUE TITLE
Unable to change i2c address

### ISSUE THREAD

**Issue by giddy123** [sparkfun/SparkFun_LIDARLitev4_Arduino_Library#1]
I am using your default library and unable to change the i2c address. The code compiles and runs but I get a message that address change failed. I tried this on two different lidars and two different arduinos: nano and mega. I am using a logic-level shifter to step the voltage down to 3.3v for the device. Also, both lidars are working and I can get distance from them. I can have both of them working using multiplexer but I would rather change the i2c address.

**Comment by makin-stuff** [comment]
Hey there giddy123,
Can you please give me some more info about your set up? Have you been using our examples? Because I've just tested both Example2_ChangeI2CAddress and Example3_2LIDARS and they work as expected. I've successfully changed the address of one of my LIDARs and then can get readings from two LIDARs on the same I2C bus. However, sometimes I do need to run Example 2 a couple of times to get the new address to stick. This might have something to do with the fact that the GARMIN LIDAR can operate under two I2C address (datasheet pg 6).

**Comment by giddy123** [comment]
Ok, this could be the issue. I bought your regular LidarLite v4 instead of Quiic one. Does it matter? Your Example1_GetDistance example works but Example2_ChangeI2CAddress does not. If that's the case, any help with changing the address on the regular LidarLite v4?

**Comment by makin-stuff** [comment]
The examples should work on a LIDAR without the qwiic board as long as you're powering it with 5V (I2C @ 3.3V). Where exactly in the example does the address change fail? What error message do you get? What exactly are you passing into the serial monitor?

**Comment by giddy123** [comment]
Yes, I am powering the lidar with 5v and I2C @3.3v via logic shifter. I am able to obtain the distance readings. I have attached the output of the serial monitor.
![Serial_Monitor_Lidar_v4](https://user-images.githubusercontent.com/889838/80638854-f1915000-8a15-11ea-837a-365f3aef7316.png)

**Comment by giddy123** [comment]
Just to add, I tried setting the line ending to "Both NL & CR" and "Newline" but it doesn't make any difference

**Comment by giddy123** [comment]
After some troubleshooting, I see that it fails after this line of LidarLite_v4LED.cpp

**bool success = write(UNIT_ID_0, dataBytes, 5);**

It does return success as 1 but it's failing at this line: "return false" below.

   while (1)
    {
        delay(50);

        if (isConnected() == true) {
		         break;			
		}
        if (counter++ > 100)
        {
            //LIDAR never responded
                      return false;
        }
    }

Any help? Thank you!

**Comment by MechaPhoton** [comment]
hi , just wanted to say im having the exact same issue.

**Comment by makin-stuff** [comment]
Hi there @icpxl and @giddy123. Think I found the source of the problem. The function setI2Caddr() writes the 4 serial number bytes in reverse order. I've fixed and published a new release. Please pull the most recent or update library in the Arduino library manager. Closing this issue for now. Cheers.
